[package]
name = "weather"
version = "0.1.0"
authors = ["Alastair Smith <alastair.smith@korelogic.co.uk>"]
edition = "2018"
description = "A weather CLI App"

[dependencies]
clap = {version ="2.33.0", features = ["yaml"]}
failure = "0.1.5"
reqwest = "0.9.18"
serde = "1.0.92"
dotenv = "0.15.0"